name: Send Engagement Emails

on:
  schedule:
    # Her gün saat 10:00'da çalış (UTC)
    - cron: '0 10 * * *'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  send-emails:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Engagement Emails
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/send-engagement-emails?dryRun=false&minDays=5&maxEmails=30" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
